FROM ruby:2.7
RUN curl -sS https://dl.yarnpkg......................see_https://www.youtube.com/watch?v=lZD1MIHwMBY

WORKDIR /app
COPY .src /app/
RUN bundle config --local set path 'vendor/bundle' \
  && bundle install
